apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbapp
  namespace: argocd # The namespace where ArgoCD is installed
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Deletes K8s resources when the app is deleted
spec:
  project: default # ArgoCD project for grouping and permissions
  source:
    repoURL: 'https://github.com/networknuts/argocd.git' # Source Git repository
    targetRevision: HEAD # Target branch, tag, or commit hash
    path: ch-13/secret-app # Path containing Kubernetes manifests inside the repo
  destination:
    server: 'https://kubernetes.default.svc' # Target cluster URL (internal cluster)
    namespace: default # Target namespace for your application resources
  syncPolicy:
    automated:
      prune: true # Automatically deletes resources removed from Git
      selfHeal: true # Automatically fixes drift if cluster resources change manually
    syncOptions:
      - CreateNamespace=true # Creates target namespace automatically if it doesn't exist
