apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # 1. Services: Define where notifications go
  service.slack: |
    token: $slack-token

  # 2. Templates: Define the message format
  template.app-sync-succeeded: |
    message: |
      🎉 Application **{{.app.metadata.name}}** synced successfully!
      Revision: {{.app.status.sync.revision}}
      View details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  # 3. Triggers: Define the conditions for sending
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]
  # 4. Template used for failed deployments
  template.app-sync-failed: |
    message: |
      🚨 **Application {{.app.metadata.name}} deployment failed.**
      Revision: {{.app.status.sync.revision}}
      Message: {{.app.status.operationState.message}}
      Details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  # --- TRIGGERS ---
  # Trigger that activates when the phase is Succeeded and the health is Healthy
  trigger.on-deployed: |
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.operationState.finishedAt
      send:
        - app-sync-success

  # Trigger that activates when the phase is Error or Failed
  trigger.on-deploy-failed: |
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
      oncePer: app.status.operationState.finishedAt
      send:
        - app-sync-failed
   # 1. Define the custom deletion trigger
  trigger.on-app-deleted: |
    - description: Application deletion has been initiated.
      when: app.metadata.deletionTimestamp != nil
      send:
        - app-deleted-slack-notification

  # 2. Define the payload template (Slack example)
  template.app-deleted-slack-notification: |
    message: |
      ⚠️ Application {{.app.metadata.name}} is being deleted!
    slack:
      attachments: |
        [{
          "title": "Argo CD Alert: Application Deletion Initiated",
          "color": "#FF0000",
          "fields": [
            {"title": "Application Name", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Project", "value": "{{.app.spec.project}}", "short": true},
            {"title": "Cluster", "value": "{{.app.spec.destination.server}}", "short": false},
            {"title": "Namespace", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Deletion Initiated At", "value": "{{.app.metadata.deletionTimestamp}}", "short": false}
          ]
        }]