apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    metadata:
      labels:
        environment: staging
    spec:
      containers:
        - name: boxone
          image: nginx:latest
          resources:
            limits:
              cpu: 20m
              memory: 30Mi
            requests:
              cpu: 20m
              memory: 30Mi