---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-dbcreds
  namespace: default
spec:
  encryptedData:
    password: AgB5dFFFTpqCuhLtoO0l9jlkOJvmhbwp+t2au2o1dbdKA0o/VJ2FcC5KmHqtbikJi53xTEBB6tb0rYWUdXB3BuI82+btTukOx5V/ScHEDB0aE8Nl1sXKai2+p5VNGr0X5/+y3soBSXo0ansQLcOmAvLSV0ZgN8LkdBJyh0VFa8wLtDuSdT90iLHxobs5KA294avzXm6zdljR+YpNNd6VWxRWqJnEMJ5dXtCBm5hIJAVjlc8erLJoaCPFPOnSae057JFk1BmEhgkT8NDixsJA5QY5Ki2X2OBab05NB87cw1EHMqZjgphlJMI2k0xHHNq/X8ACUHDb7Tw/kSKqy9bJiQ+5XQEpcM9XrpENKiPVQQm3o/yTpsm8VvXKDwyFAnzrqiWvTi3GMABbr+8oEbD1M0ElMuSIGhLPLK4i1YboG7KzhnDhY8143ZNHUnZ7R6THbGdP2UM9HqA3bZY603bJ2HeRfCP7dKfamCcM1tBnFFOlkP5EwvaVMg+XzZ85YRn0V3ZylNfslL8vJeyuoC7Z4PbNsFsRf85aUTLrIspxnPYkRo5XiCdedR9E13XnVFekowq3cjofQOgX0dBuP48VpMGzKv+M424ros0zSaphREmYHRjRKyhmToLagtp5QoCHEoc3NydLVXsyt/2u1eHT3t1DiEYp0YgnXHE8dLRrk4DeeDtNtAuvTUd8fjKS1BUNX8A8O480N3b40WoRwvxHQdogBg==
    username: AgCShU0T3ALoYvN/YBoQFfzXKNdVEPGcTws7eHqE/JXM5q2VfbzVnIcvql8wH5tZHR2fwkSVGYdHOLiSsMpXRtZLYMnQVmgmEg1KCev5YtMF4cp6OhfbylsxiHKAInRUUPQiPjHgkrS2GaFDFtHiBAmdRtGfRT1bteR+EmYAqUvwDb6HTTafT8+g5mMooX7T536eijG4mWH8/Bpy7llNk/MKtTMsGccVJYYPK9CEFwPkUw82U8+RGSWGJdPKgcxjaXz10fMlxkwX20X12SmaJM/U7FBL5E9+9et1M8p37llRszuEawBkm7CamfNL9mRmOteBkO0Y5t+mORfLq6BPN34xpzU3qdTBlh05SxuN5iH8kmpVTLMe76NFgMSHm9qXBjy3rDGF36mOghSrC3tdDNTEdIVhNx/mvfxj9f3XmTBHR6Ztfd2zIm2UeSKi2QssVAiy0TwD0JL7ao/ccnTmGKPdrr1ePscNHMMLOSA2of4k0Wv52m3rgotp5xr3vND2edsbBjddDpdBpGlPVyej+ZQM/9wCxOX0+18TlVP/VNS3jhRhTtgvWyS+lGNjMR7+2PV7Mz0P7/K0NGAb/Bce2lJZCyH2Y/ZyDxMjSxDdFFrJ41ATvLAIarSrLxy5ZnamEu7/4i74zT3MeFcoD8hA/jnaSoWTNhpxxKtcKnhKcPVy92M6d/aj6T4YJnxu4Lkk6l1V3826tQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-dbcreds
      namespace: default